# Generated by Django 5.0.2 on 2026-02-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_screenshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredpage',
            name='region_height_pct',
            field=models.FloatField(default=1.0, help_text='Monitored region height as fraction (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='region_left_pct',
            field=models.FloatField(default=0.0, help_text='Monitored region left position as fraction (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='region_top_pct',
            field=models.FloatField(default=0.0, help_text='Monitored region top position as fraction (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='region_width_pct',
            field=models.FloatField(default=1.0, help_text='Monitored region width as fraction (0.0-1.0)'),
        ),
    ]
