# Generated by Django 5.0.2 on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_region_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredpage',
            name='change_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Enable notifications for visual changes'),
        ),
    ]

