# Generated by Django 5.0.2 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_change_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredpagecheck',
            name='crop_path',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Region-cropped screenshot used for diffing (empty when full-page)',
                max_length=512,
            ),
        ),
    ]

