# Generated by Django 5.0.2 on 2026-02-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_add_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredpage',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
    ]
